/**
 * tests/e2e/export.e2e.spec.ts — the EXPORT (P3) E2E (plan E.5 done-when /
 * PRD §18 "export produces a non-empty file; assert streamed progress events").
 *
 * Drives the FULL export path against the REAL built Electron app: the renderer
 * `runExport` orchestration → real `jobs.start('export')` over the IPC →
 * out-of-band transferred MessagePort → real `SidecarManager` → the real
 * `export` runner → the REAL ffmpeg (ffmpeg-static, which HAS h264_videotoolbox)
 * on a synthetic fixture. Asserts:
 *   - the streamed progress events reach the renderer (≥1 progress, ending 100),
 *   - the export `done` result is 1080×1920,
 *   - a NON-EMPTY mp4 file is written to the chosen output path.
 *
 * The source video is generated by ffmpeg-static in the test; `OPENCLIP_FFMPEG`
 * is passed to the app so the production-NODE_ENV main process resolves the same
 * binary (it would otherwise look under process.resourcesPath). Skips gracefully
 * if ffmpeg-static is unavailable.
 */

import { test, expect, _electron as electron } from '@playwright/test'
import { join } from 'node:path'
import { mkdtempSync, existsSync, statSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { tmpdir } from 'node:os'

function ffmpegStatic(): string | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const p = require('ffmpeg-static') as string | null
    return p && existsSync(p) ? p : null
  } catch {
    return null
  }
}

const FFMPEG = ffmpegStatic()

test('Export P3: a clip exports to a non-empty 1080×1920 mp4 with streamed progress', async () => {
  test.skip(!FFMPEG, 'ffmpeg-static not available')

  const work = mkdtempSync(join(tmpdir(), 'openclip-export-e2e-'))
  const src = join(work, 'src.mp4')
  const out = join(work, 'exported-clip.mp4')

  // Synthetic 6s 1920×1080 30fps source (so the 9:16 center-crop has room).
  const gen = spawnSync(
    FFMPEG!,
    [
      '-hide_banner',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc2=size=1920x1080:rate=30:duration=6',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=6',
      '-g',
      '12',
      '-c:v',
      'libx264',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      src
    ],
    { encoding: 'utf8' }
  )
  expect(gen.status).toBe(0)

  const userDataDir = mkdtempSync(join(tmpdir(), 'openclip-export-userdata-'))
  const app = await electron.launch({
    args: [join(process.cwd(), 'out', 'main', 'index.js'), `--user-data-dir=${userDataDir}`],
    env: {
      ...process.env,
      NODE_ENV: 'production',
      OPENCLIP_FAKE_TRANSCRIBE: '1',
      // Make the production main process resolve the same ffmpeg the test used.
      OPENCLIP_FFMPEG: FFMPEG!
    }
  })
  const win = await app.firstWindow()
  await win.waitForLoadState('domcontentloaded')

  const result = await win.evaluate(
    async ({ src, out }) => {
      const h = window.__openclipTest!
      const progress: number[] = []
      const r = await h.runExport({
        bridge: window.openclip,
        params: {
          projectId: 'export-e2e',
          clipId: 'clip-1',
          sourcePath: src,
          startTime: 1.0,
          endTime: 3.5,
          aspectRatio: '9:16',
          outputPath: out,
          quality: '1080p'
        },
        onProgress: (p) => progress.push(p)
      })
      return { r, progress }
    },
    { src, out }
  )

  // Streamed progress reached the renderer and ended at 100 (terminal done).
  expect(result.progress.length).toBeGreaterThan(0)
  expect(result.progress[result.progress.length - 1]).toBe(100)

  // The export result is a 1080×1920 clip.
  expect(result.r.width).toBe(1080)
  expect(result.r.height).toBe(1920)
  expect(result.r.outputPath).toBe(out)

  // A NON-EMPTY mp4 file was actually written (PRD §18).
  expect(existsSync(out)).toBe(true)
  expect(statSync(out).size).toBeGreaterThan(0)

  await app.close()
})
