/**
 * tests/e2e/packaged-app.e2e.spec.ts — the GATE-D packaged-app smoke (PRD §13,
 * plan E.6/E.7 Gate D). The real value of Stage 2: prove the SHIPPED .app runs
 * the full flow with binaries resolved from `Contents/Resources` — NOT from
 * node_modules.
 *
 * Unlike the other E2E specs (which launch `out/main/index.js` with
 * OPENCLIP_FFMPEG / OPENCLIP_FAKE_TRANSCRIBE overrides), this one launches the
 * actual packaged executable
 *   dist/mac-arm64/OpenClip.app/Contents/MacOS/OpenClip
 * with **NO** OPENCLIP_* overrides and NODE_ENV unset — so `app.isPackaged` is
 * true and `src/main/utils/paths.ts` resolves ffmpeg/ffprobe/whisper-cli/fonts
 * from `process.resourcesPath` (the prod path). It then:
 *
 *   1. asserts the diagnostic IPC reports binary paths INSIDE the .app bundle
 *      (and explicitly NOT under node_modules) — the load-bearing Gate-D proof;
 *   2. runs a REAL flow through the renderer orchestration + real bridge + real
 *      SidecarManager + the BUNDLED binaries:
 *        generate a 1920×1080 source (bundled ffmpeg) → import (bundled ffprobe)
 *        → audio extract (bundled ffmpeg) → transcribe with the REAL tiny GGML
 *        model (bundled whisper-cli, Metal) → export a captioned 1080×1920 mp4
 *        (bundled ffmpeg + libass + the bundled DejaVuSans.ttf fontsdir).
 *
 * Requires a packaged .app (Stage 2 `npm run build:mac:unsigned`) and the real
 * tiny model staged at `.smoke-cache/models/ggml-tiny.bin`. Skips gracefully
 * (not fails) when either is absent so a clean checkout / CI without them is OK.
 */

import { test, expect, _electron as electron } from '@playwright/test'
import { join } from 'node:path'
import { mkdtempSync, existsSync, statSync, mkdirSync, copyFileSync } from 'node:fs'
import { spawnSync, execFileSync } from 'node:child_process'
import { tmpdir } from 'node:os'

const APP_DIR = join(process.cwd(), 'dist', 'mac-arm64', 'OpenClip.app')
const APP_EXE = join(APP_DIR, 'Contents', 'MacOS', 'OpenClip')
const APP_RESOURCES = join(APP_DIR, 'Contents', 'Resources')
const BUNDLED_FFMPEG = join(APP_RESOURCES, 'ffmpeg', 'darwin-arm64', 'ffmpeg')
const BUNDLED_FFPROBE = join(APP_RESOURCES, 'ffmpeg', 'darwin-arm64', 'ffprobe')
// Auto-reframe (Part J): the YuNet model + onnxruntime-web wasm ship under
// <Resources>/onnx (electron-builder extraResources → paths.ts reframeOnnxDir()).
const BUNDLED_ONNX_MODEL = join(APP_RESOURCES, 'onnx', 'face_detection_yunet_2023mar.onnx')
const BUNDLED_ONNX_WASM = join(APP_RESOURCES, 'onnx', 'ort-wasm-simd-threaded.wasm')
const TINY_MODEL = join(process.cwd(), '.smoke-cache', 'models', 'ggml-tiny.bin')

const HAVE_APP = existsSync(APP_EXE) && existsSync(BUNDLED_FFMPEG)
const HAVE_MODEL = existsSync(TINY_MODEL)

// This smoke runs the REAL whisper-cli on Metal + two real ffmpeg encodes; give
// it room (transcribe of a few seconds of audio + an export re-encode).
test.setTimeout(180_000)

test('Gate D: the packaged .app runs the full flow with binaries from Contents/Resources', async () => {
  test.skip(!HAVE_APP, 'no packaged .app — run `npm run build:mac:unsigned` first')
  test.skip(!HAVE_MODEL, 'no .smoke-cache/models/ggml-tiny.bin — stage the tiny model first')

  // A clean per-run userData with the tiny model staged into models/ so the
  // production `isModelInstalled('tiny')` gate (userData/models/ggml-tiny.bin)
  // passes and a REAL transcribe runs from the bundle.
  const userDataDir = mkdtempSync(join(tmpdir(), 'openclip-gated-userdata-'))
  mkdirSync(join(userDataDir, 'models'), { recursive: true })
  copyFileSync(TINY_MODEL, join(userDataDir, 'models', 'ggml-tiny.bin'))

  const work = mkdtempSync(join(tmpdir(), 'openclip-gated-work-'))
  const src = join(work, 'src.mp4')
  const out = join(work, 'captioned-clip.mp4')

  // Synthetic 5s 1920×1080 30fps source generated by the BUNDLED ffmpeg itself
  // (further proof the bundled binary runs). Audio is a 440Hz sine so whisper
  // has a signal to decode (it will emit few/no words — that's fine; we assert
  // the pipeline completes + the captioned export probes correctly, not ASR
  // accuracy on a sine tone).
  const gen = spawnSync(
    BUNDLED_FFMPEG,
    [
      '-hide_banner',
      '-y',
      '-f',
      'lavfi',
      '-i',
      'testsrc2=size=1920x1080:rate=30:duration=5',
      '-f',
      'lavfi',
      '-i',
      'sine=frequency=440:duration=5',
      '-g',
      '12',
      '-c:v',
      'libx264',
      '-pix_fmt',
      'yuv420p',
      '-c:a',
      'aac',
      '-shortest',
      src
    ],
    { encoding: 'utf8' }
  )
  expect(gen.status, gen.stderr).toBe(0)
  expect(existsSync(src)).toBe(true)

  // Launch the REAL packaged executable. Critically: NO OPENCLIP_* overrides and
  // NODE_ENV unset, so prod resolution (process.resourcesPath) is exercised.
  const STRIP = new Set([
    'NODE_ENV',
    'ELECTRON_RENDERER_URL',
    'OPENCLIP_FFMPEG',
    'OPENCLIP_FFPROBE',
    'OPENCLIP_WHISPER_CLI',
    'OPENCLIP_FONTS_DIR',
    'OPENCLIP_FAKE_TRANSCRIBE'
  ])
  const env: Record<string, string> = {}
  for (const [k, v] of Object.entries(process.env)) {
    if (v !== undefined && !STRIP.has(k)) env[k] = v
  }

  const app = await electron.launch({
    executablePath: APP_EXE,
    args: [`--user-data-dir=${userDataDir}`],
    env
  })

  try {
    const win = await app.firstWindow()
    await win.waitForLoadState('domcontentloaded')

    // (0) BLANK-WINDOW REGRESSION GUARD (F.5 / G.4): in the PACKAGED file:// build
    // the module script must execute (a CSP/meta/title regression would leave a
    // blank window). Prove the title is correct AND that React actually mounted
    // (#root has rendered children — the welcome screen on first run).
    expect(await win.title()).toBe('OpenClip')
    await win.waitForFunction(
      () => {
        const root = document.getElementById('root')
        return !!root && root.children.length > 0
      },
      { timeout: 10_000 }
    )
    await expect(win.getByTestId('welcome')).toBeVisible()

    // (1) PROVE prod binary resolution: the diagnostic IPC must report binary
    // paths INSIDE the .app bundle and NOT under node_modules.
    const resolved = await win.evaluate(async () => {
      // window.electron is exposed by @electron-toolkit/preload (contextIsolated).
      const w = window as unknown as {
        electron: { ipcRenderer: { invoke(ch: string): Promise<unknown> } }
      }
      return (await w.electron.ipcRenderer.invoke('diag:resolved-paths')) as {
        resourcesPath: string
        isPackaged: boolean
        ffmpeg: string
        ffprobe: string
        whisperCli: string
        fontsDir: string
      }
    })

    // The app must believe it is packaged (prod path).
    expect(resolved.isPackaged).toBe(true)
    // Every resolved sidecar/font path lives under the bundle's Resources …
    expect(resolved.ffmpeg).toBe(BUNDLED_FFMPEG)
    expect(resolved.ffprobe).toBe(BUNDLED_FFPROBE)
    expect(resolved.whisperCli).toBe(join(APP_RESOURCES, 'whisper', 'darwin-arm64', 'whisper-cli'))
    expect(resolved.fontsDir).toBe(join(APP_RESOURCES, 'fonts'))
    // … and NONE of them come from node_modules (the dev path).
    for (const p of [resolved.ffmpeg, resolved.ffprobe, resolved.whisperCli, resolved.fontsDir]) {
      expect(p).toContain('OpenClip.app/Contents/Resources')
      expect(p).not.toContain('node_modules')
    }

    // (1b) AUTO-REFRAME ASSETS (Part J): the YuNet model + the onnxruntime-web
    // WASM the detector loads via `ort.env.wasm.wasmPaths` must ship under
    // Contents/Resources/onnx (extraResources → paths.ts reframeOnnxDir()), the
    // same bundle-not-node_modules guarantee as the sidecars/font above.
    expect(existsSync(BUNDLED_ONNX_MODEL)).toBe(true)
    expect(statSync(BUNDLED_ONNX_MODEL).size).toBeGreaterThan(0)
    expect(existsSync(BUNDLED_ONNX_WASM)).toBe(true)
    expect(statSync(BUNDLED_ONNX_WASM).size).toBeGreaterThan(0)
    expect(BUNDLED_ONNX_MODEL).toContain('OpenClip.app/Contents/Resources')
    expect(BUNDLED_ONNX_WASM).toContain('OpenClip.app/Contents/Resources')

    // (2) RUN THE FULL FLOW through the real renderer orchestration → real bridge
    // → real SidecarManager → BUNDLED binaries. import+extract+REAL transcribe.
    const flow = await win.evaluate(
      async ({ src, out }) => {
        const h = window.__openclipTest!
        const progress: number[] = []

        const imported = await h.runImportPipeline({
          bridge: window.openclip,
          filePath: src,
          projectId: 'gate-d',
          model: 'tiny',
          onProgress: (p) => progress.push(p)
        })

        // Build word timestamps to burn as karaoke captions. Use whatever the
        // real transcribe produced; if a sine tone yields no words, synthesize a
        // couple so the libass burn + bundled-font path is still exercised.
        const words =
          imported.transcript.words.length > 0
            ? imported.transcript.words
            : [
                { word: 'OPEN', start: 0.2, end: 0.9, confidence: 1 },
                { word: 'CLIP', start: 0.9, end: 1.6, confidence: 1 }
              ]

        const exportProgress: number[] = []
        const result = await h.runExport({
          bridge: window.openclip,
          params: {
            projectId: 'gate-d',
            clipId: 'clip-1',
            sourcePath: src,
            startTime: 0.5,
            endTime: 3.0,
            aspectRatio: '9:16',
            outputPath: out,
            quality: '1080p',
            captions: { words }
          },
          onProgress: (p) => exportProgress.push(p)
        })

        return {
          sourceVideo: imported.sourceVideo,
          wordCount: imported.transcript.words.length,
          language: imported.transcript.language,
          importProgress: progress,
          exportProgress,
          result
        }
      },
      { src, out }
    )

    // Import probed real metadata from the bundled ffprobe.
    expect(flow.sourceVideo.resolution.width).toBe(1920)
    expect(flow.sourceVideo.resolution.height).toBe(1080)
    // Transcribe streamed to completion (terminal done → 100).
    expect(flow.importProgress[flow.importProgress.length - 1]).toBe(100)
    // Export streamed progress and reported a 1080×1920 clip.
    expect(flow.exportProgress.length).toBeGreaterThan(0)
    expect(flow.exportProgress[flow.exportProgress.length - 1]).toBe(100)
    expect(flow.result.width).toBe(1080)
    expect(flow.result.height).toBe(1920)

    // (3) The exported captioned mp4 exists, is non-empty, and ffprobes as a real
    // 1080×1920 H.264 video — verified with the BUNDLED ffprobe.
    expect(existsSync(out)).toBe(true)
    expect(statSync(out).size).toBeGreaterThan(0)

    const probe = execFileSync(
      BUNDLED_FFPROBE,
      [
        '-v',
        'error',
        '-select_streams',
        'v:0',
        '-show_entries',
        'stream=width,height,codec_name',
        '-of',
        'json',
        out
      ],
      { encoding: 'utf8' }
    )
    const stream = (
      JSON.parse(probe) as { streams: { width: number; height: number; codec_name: string }[] }
    ).streams[0]
    expect(stream.width).toBe(1080)
    expect(stream.height).toBe(1920)
    expect(stream.codec_name).toBe('h264')
  } finally {
    await app.close()
  }
})
