/**
 * ExportPanel — pick a clip, choose an output folder (save dialog), run the
 * export with live progress, then "open folder" (EXPORT spine, plan E.5;
 * PRD §6.9 / §11.2). The pure orchestration (save dialog → export job → reveal)
 * lives in `export-run.ts` (unit-tested against the mock bridge); this is the UI
 * shell. The exported clip set reflects LIVE slice state via
 * `composeProject()` + `buildExportParams()` (integration-gap fix, task 5).
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useProjectStore } from '@renderer/stores/projectStore'
import { useSettingsStore } from '@renderer/stores/settingsStore'
import { useBrandStore, activeBrand } from '@renderer/stores/brandStore'
import { trackTask, useJobsStore } from '@renderer/stores/jobsStore'
import { buildExportParams } from '@renderer/stores/projectStore/exportSlice'
import {
  exportToFile,
  openExportFolder,
  defaultClipFileName
} from '@renderer/components/export-run'
import { runBatchExport } from '@renderer/components/batch-export'
import { PLATFORM_PRESETS, platformPreset } from '@renderer/components/platformPresets'
import { CAPTION_PRESETS, resolveEffectiveCaptionStyle } from '@renderer/components/captionPresets'
import { brandCaptionOverride, brandLogoParams } from '@renderer/components/brandKit'
import { fetchAiEmojiMap } from '@renderer/components/caption-emoji'
import { resolveBounds } from '@shared/clip-bounds'
import type { AspectRatio, CaptionStyle } from '@shared/schema'
import { Button } from '@renderer/components/ui/button'
import { Progress } from '@renderer/components/ui/progress'

type Phase = 'idle' | 'exporting' | 'done' | 'error'

/**
 * Output pixel dimensions per aspect ratio for the export summary (audit fix
 * openclip-7b5 — the panel previously hard-coded "1080×1920" for every aspect).
 * Mirrors `outputDimensions()` in the main-process ffmpeg-export service, which is
 * the authoritative encoder size; kept as a tiny renderer-local map because
 * `@main` can't be imported across the process boundary.
 */
const EXPORT_DIMENSIONS: Record<AspectRatio, string> = {
  '9:16': '1080×1920',
  '1:1': '1080×1080',
  '4:5': '1080×1350',
  '16:9': '1920×1080'
}

/** A selectable caption-template chip (Part K gallery). */
function TemplateChip(props: {
  label: string
  title?: string
  active: boolean
  onClick: () => void
}): React.JSX.Element {
  return (
    <button
      type="button"
      data-testid="caption-template-chip"
      data-active={props.active}
      title={props.title}
      onClick={props.onClick}
      className={`rounded-full border px-2.5 py-1 text-xs transition-colors ${
        props.active
          ? 'border-primary bg-primary text-primary-foreground'
          : 'border-border bg-background hover:bg-accent'
      }`}
    >
      {props.label}
    </button>
  )
}

export function ExportPanel(): React.JSX.Element {
  const currentProject = useProjectStore((s) => s.currentProject)
  const clips = useProjectStore((s) => s.clips)
  const selectedClipId = useProjectStore((s) => s.selectedClipId)
  const selectClip = useProjectStore((s) => s.selectClip)
  const composeProject = useProjectStore((s) => s.composeProject)
  const addExportRecord = useProjectStore((s) => s.addExportRecord)
  const markExported = useProjectStore((s) => s.markExported)
  const setProjectSettings = useProjectStore((s) => s.setProjectSettings)
  // Part K: reframe lives in the shared previewSlice so the preview badge + the
  // export use one source of truth.
  const reframe = useProjectStore((s) => s.reframeMode)
  const setReframe = useProjectStore((s) => s.setReframeMode)

  const transcript = useProjectStore((s) => s.transcript)

  // Part K — the AI emoji provider/model lives in app Settings; the active brand
  // (per-project) drives caption colors/font + the logo overlay.
  const settings = useSettingsStore((s) => s.settings)
  const brands = useBrandStore((s) => s.brands)
  const brandLoaded = useBrandStore((s) => s.loaded)
  const loadBrands = useBrandStore((s) => s.load)
  useEffect(() => {
    if (!brandLoaded) void loadBrands()
  }, [brandLoaded, loadBrands])

  const [pct, setPct] = useState(0)
  const [phase, setPhase] = useState<Phase>('idle')
  const [err, setErr] = useState<string | null>(null)
  const [outputPath, setOutputPath] = useState<string | null>(null)
  // Burn word-level karaoke captions into the export (PRD §6.4). On by default
  // when the project has transcript words; the .ass is generated by the runner.
  const [captionsEnabled, setCaptionsEnabled] = useState(true)
  // Remove long silences via jump-cuts (Part I.4, opt-in, default off).
  const [removeSilence, setRemoveSilence] = useState(false)

  const words = transcript?.words ?? currentProject?.transcript.words ?? []
  const hasWords = words.length > 0

  // The clip to export: the explicitly-selected one, else the first clip.
  const clip = useMemo(
    () => clips.find((c) => c.id === selectedClipId) ?? clips[0] ?? null,
    [clips, selectedClipId]
  )
  const span = clip ? resolveBounds(clip) : null
  const aspectRatio = currentProject?.settings.aspectRatio ?? '9:16'
  // Caption template (Part K) — PERSISTED on the project so the export and the
  // (Step 3) WYSIWYG preview always agree. '' ⇒ the app-default karaoke style.
  const captionTemplateId = currentProject?.settings.captionTemplateId ?? ''
  // Auto-emoji source (Part K) — persisted on the project so the preview agrees.
  const autoEmoji: CaptionStyle['autoEmoji'] = currentProject?.settings.autoEmoji ?? 'off'
  // The active brand (per-project selection resolved against the app library).
  const brand = activeBrand(brands, currentProject?.activeBrandId)

  const runExport = useCallback(async (): Promise<void> => {
    if (!clip || !currentProject) return
    // Compose from LIVE slices so the exported span/source reflect current edits.
    const project = composeProject()
    if (!project) return

    setPhase('exporting')
    setErr(null)
    setPct(0)
    setOutputPath(null)
    try {
      // Auto-emoji 'ai' (Part K): fetch the BYOK emoji map BEFORE the job (the
      // buildParams callback is sync). Best-effort — undefined ⇒ no AI emoji.
      const aiEmojiMap = await fetchAiEmojiMap({
        bridge: window.openclip,
        settings,
        words: project.transcript.words,
        clip,
        autoEmoji
      })
      // Tracked in the app-level registry so the encode stays visible and
      // cancellable after this dialog closes — Escape or a backdrop click used
      // to orphan a running ffmpeg with no consumer (EPIC-zpa1nd).
      const outcome = await trackTask(
        {
          kind: 'export',
          label: clip.title,
          // Mirror the runner's own `willAnalyze` branch so the checklist shows
          // the stages this particular export will really pass through.
          stages: removeSilence || reframe !== 'off' ? ['analyzing', 'encoding'] : ['encoding']
        },
        async (task) => {
          const result = await exportToFile({
            bridge: window.openclip,
            defaultFileName: defaultClipFileName(clip.title),
            onStart: (jobId) => task.setCancel(() => window.openclip.jobs.cancel(jobId)),
            buildParams: (chosenPath) =>
              buildExportParams({
                projectId: project.id,
                clip,
                source: project.sourceVideo,
                settings: project.settings,
                outputPath: chosenPath,
                captionsEnabled: captionsEnabled && hasWords,
                words: project.transcript.words,
                // Brand overrides caption font/colors; autoEmoji selects the emoji source.
                captionStyle: resolveEffectiveCaptionStyle(captionTemplateId, {
                  autoEmoji,
                  brand: brandCaptionOverride(brand)
                }),
                aiEmojiMap,
                // Brand logo overlay (Part K) — {} when the brand has no logo.
                ...brandLogoParams(brand),
                removeSilence,
                reframe
              }),
            onProgress: (p) => {
              setPct(Math.round(p))
              task.progress(p, 'encoding')
            }
          })
          // The save dialog was dismissed: no job ran, so there is nothing to
          // report as finished OR failed — drop the row rather than invent one.
          if (result.canceled) task.abandon()
          else task.setOutputPath(result.outputPath)
          return result
        }
      )
      if (outcome.canceled) {
        setPhase('idle')
        return
      }
      setOutputPath(outcome.outputPath)
      addExportRecord({
        id: `exp-${Date.now().toString(36)}`,
        clipId: clip.id,
        outputPath: outcome.outputPath,
        exportedAt: Date.now(),
        width: outcome.result.width,
        height: outcome.result.height,
        format: 'mp4'
      })
      setPhase('done')
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
      setPhase('error')
    }
  }, [
    clip,
    currentProject,
    composeProject,
    addExportRecord,
    captionsEnabled,
    hasWords,
    captionTemplateId,
    autoEmoji,
    brand,
    settings,
    removeSilence,
    reframe
  ])

  const reveal = useCallback(async (): Promise<void> => {
    if (outputPath) await openExportFolder(window.openclip, outputPath)
  }, [outputPath])

  // ── Batch export (Part K, Step 4): all APPROVED clips → one folder ──────────
  const [platformId, setPlatformId] = useState('tiktok')
  const [batch, setBatch] = useState<{
    running: boolean
    total: number
    done: number
    failed: number
  } | null>(null)
  const batchAbort = useRef<AbortController | null>(null)
  const approvedClips = useMemo(() => clips.filter((c) => c.status === 'approved'), [clips])

  const runBatch = useCallback(async (): Promise<void> => {
    const project = composeProject()
    const preset = platformPreset(platformId)
    if (!project || !preset || approvedClips.length === 0) return
    const dir = await window.openclip.system.directoryDialog({})
    if (dir.canceled || !dir.dirPath) return

    const controller = new AbortController()
    batchAbort.current = controller
    setBatch({ running: true, total: approvedClips.length, done: 0, failed: 0 })

    // One parent row for the batch plus a child row per clip. `onClipProgress`
    // has existed on runBatchExport since it was written and was never passed,
    // so ten concurrent encodes reported as a single "3/10 exported" counter
    // with no way to see which clip was slow or which one failed (FEAT-ckxz8d).
    const jobs = useJobsStore.getState()
    const batchTaskId = jobs.beginTask({
      kind: 'batch-export',
      label: `${approvedClips.length} clips`,
      cancel: async () => controller.abort()
    })
    const childIds = new Map<string, string>()

    const results = await runBatchExport({
      bridge: window.openclip,
      project,
      clips: approvedClips,
      dir: dir.dirPath,
      preset,
      // Part K — apply the active brand (caption colors/font + logo) and the
      // auto-emoji source to every clip; the AI map is fetched per clip.
      brand,
      autoEmoji,
      resolveAiEmojiMap: (c) =>
        fetchAiEmojiMap({
          bridge: window.openclip,
          settings,
          words: project.transcript.words,
          clip: c,
          autoEmoji
        }),
      signal: controller.signal,
      onClipProgress: (clipId, pct) => {
        const childId = childIds.get(clipId)
        if (childId) useJobsStore.getState().updateTask(childId, { pct, stage: 'encoding' })
      },
      onClipStatus: (clipId, status, info) => {
        const store = useJobsStore.getState()
        if (status === 'running') {
          const title = approvedClips.find((c) => c.id === clipId)?.title ?? clipId
          childIds.set(
            clipId,
            store.beginTask({ kind: 'export', label: title, parentId: batchTaskId })
          )
        } else {
          const childId = childIds.get(clipId)
          // Keep the per-clip FAILURE MESSAGE, which the old counter discarded:
          // "3 failed" cannot be acted on, "clip-4: No space left on device" can.
          if (childId) store.settleTask(childId, status, { error: info?.error })
        }
        setBatch((b) =>
          b
            ? {
                ...b,
                done: b.done + (status === 'done' ? 1 : 0),
                failed: b.failed + (status === 'error' || status === 'canceled' ? 1 : 0)
              }
            : b
        )
      }
    })

    const exported: string[] = []
    for (const r of results) {
      if (r.status === 'done' && r.result) {
        exported.push(r.clipId)
        addExportRecord({
          id: `exp-${Date.now().toString(36)}-${r.clipId}`,
          clipId: r.clipId,
          outputPath: r.outputPath,
          exportedAt: Date.now(),
          width: r.result.width,
          height: r.result.height,
          format: 'mp4'
        })
      }
    }
    if (exported.length) markExported(exported)
    setBatch((b) => (b ? { ...b, running: false } : b))

    // Settle the parent. "Reveal" is pointed at the first exported FILE rather
    // than the folder, because the main handler reveals a path INSIDE its
    // parent — handing it the directory would open the directory's parent.
    const failures = results.filter((r) => r.status === 'error')
    const firstOutput = results.find((r) => r.status === 'done')?.outputPath
    useJobsStore.getState().settleTask(batchTaskId, failures.length === 0 ? 'done' : 'error', {
      outputPath: firstOutput,
      detail: { itemsDone: exported.length, itemsTotal: results.length },
      error:
        failures.length > 0
          ? `${failures.length} of ${results.length} clips failed — see the rows below.`
          : undefined
    })
    batchAbort.current = null
  }, [
    composeProject,
    platformId,
    approvedClips,
    addExportRecord,
    markExported,
    brand,
    autoEmoji,
    settings
  ])

  return (
    <div data-testid="export-panel" className="flex flex-col gap-3 p-3 text-sm">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Export
      </h2>

      {!clip && (
        <p className="text-muted-foreground" data-testid="export-no-clip">
          No clip selected — generate or pick a clip first.
        </p>
      )}

      {clip && (
        <>
          <div className="flex flex-col gap-1">
            <span className="font-medium" data-testid="export-clip-title">
              {clip.title}
            </span>
            {span && (
              <span className="text-xs text-muted-foreground" data-testid="export-clip-span">
                {span.start.toFixed(2)}s – {span.end.toFixed(2)}s (
                {(span.end - span.start).toFixed(2)}s) · {aspectRatio} ·{' '}
                {EXPORT_DIMENSIONS[aspectRatio]}
              </span>
            )}
          </div>

          {/* Word-level karaoke captions toggle (PRD §6.4). */}
          <label className="flex items-center gap-2 text-xs" data-testid="export-captions-toggle">
            <input
              type="checkbox"
              checked={captionsEnabled && hasWords}
              disabled={!hasWords}
              onChange={(e) => setCaptionsEnabled(e.target.checked)}
            />
            <span className={hasWords ? '' : 'text-muted-foreground'}>
              Burn karaoke captions{hasWords ? '' : ' (no transcript)'}
            </span>
          </label>

          {/* Caption template gallery (Part K). Persisted on the project so the
              export + the WYSIWYG preview agree. A chip per template. */}
          {captionsEnabled && hasWords && (
            <div className="flex flex-col gap-1.5" data-testid="caption-template-gallery">
              <span className="text-xs text-muted-foreground">Caption template:</span>
              <div className="flex flex-wrap gap-1.5">
                <TemplateChip
                  label="Default"
                  active={captionTemplateId === ''}
                  onClick={() => setProjectSettings({ captionTemplateId: '' })}
                />
                {CAPTION_PRESETS.map((p) => (
                  <TemplateChip
                    key={p.id}
                    label={p.name}
                    title={p.description}
                    active={captionTemplateId === p.id}
                    onClick={() => setProjectSettings({ captionTemplateId: p.id })}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Auto-emoji (Part K): off / local dictionary / BYOK-AI suggestions.
              Persisted on the project so the WYSIWYG preview agrees. Monochrome
              glyphs (the bundled FFmpeg libass can't render color emoji). */}
          {captionsEnabled && hasWords && (
            <div className="flex items-center gap-2 text-xs" data-testid="auto-emoji-control">
              <span className="text-muted-foreground">Emoji:</span>
              <div className="flex overflow-hidden rounded-md border">
                {(['off', 'local', 'ai'] as const).map((mode) => (
                  <button
                    key={mode}
                    type="button"
                    data-testid={`auto-emoji-${mode}`}
                    data-active={autoEmoji === mode}
                    onClick={() => setProjectSettings({ autoEmoji: mode })}
                    className={`px-2.5 py-1 capitalize transition-colors ${
                      autoEmoji === mode
                        ? 'bg-primary text-primary-foreground'
                        : 'bg-background hover:bg-accent'
                    }`}
                  >
                    {mode === 'ai' ? 'AI' : mode}
                  </button>
                ))}
              </div>
              {autoEmoji === 'ai' && (
                <span className="text-muted-foreground">
                  uses {settings.emojiProvider ?? settings.aiProvider} (Settings)
                </span>
              )}
            </div>
          )}

          {/* Silence/filler jump-cuts (Part I.4, opt-in). */}
          <label className="flex items-center gap-2 text-xs" data-testid="remove-silence-toggle">
            <input
              type="checkbox"
              checked={removeSilence}
              onChange={(e) => setRemoveSilence(e.target.checked)}
            />
            <span>Remove silences (tighten the clip)</span>
          </label>

          {/* Auto-reframe (Part J, opt-in). Off = static center-crop. */}
          <label className="flex items-center gap-2 text-xs" data-testid="reframe-control">
            <span className="text-muted-foreground">Reframe:</span>
            <select
              data-testid="reframe-select"
              className="flex-1 rounded-md border bg-background px-2 py-1"
              value={reframe}
              onChange={(e) => setReframe(e.target.value as 'off' | 'auto' | 'split')}
            >
              <option value="off">Off (center)</option>
              <option value="auto">Follow speaker</option>
              <option value="split">Split-screen (2 people)</option>
            </select>
          </label>

          {/* Quick clip picker when multiple clips exist. */}
          {clips.length > 1 && (
            <label className="flex items-center gap-2 text-xs">
              <span className="text-muted-foreground">Clip:</span>
              <select
                data-testid="export-clip-select"
                className="flex-1 rounded-md border bg-background px-2 py-1"
                value={clip.id}
                onChange={(e) => selectClip(e.target.value)}
              >
                {clips.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.title}
                  </option>
                ))}
              </select>
            </label>
          )}

          {phase === 'exporting' && (
            <div className="flex flex-col gap-1">
              <Progress value={pct} data-testid="export-progress" />
              <span className="text-xs text-muted-foreground">{pct}%</span>
            </div>
          )}

          {phase === 'done' && (
            <span className="text-xs text-green-600" data-testid="export-done">
              Exported to {outputPath}
            </span>
          )}

          {phase === 'error' && err && (
            <span className="text-xs text-destructive" role="alert" data-testid="export-error">
              {err}
            </span>
          )}

          <div className="flex gap-2">
            <Button
              size="sm"
              data-testid="export-start"
              disabled={phase === 'exporting'}
              onClick={() => void runExport()}
            >
              {phase === 'exporting' ? 'Exporting…' : 'Export clip'}
            </Button>
            {phase === 'done' && outputPath && (
              <Button
                size="sm"
                variant="secondary"
                data-testid="export-open-folder"
                onClick={() => void reveal()}
              >
                Open folder
              </Button>
            )}
          </div>

          {/* Batch export (Part K, Step 4): every APPROVED clip → one chosen
              folder with a per-platform preset (reuses the per-clip job path). */}
          <div className="flex flex-col gap-1.5 border-t pt-3" data-testid="batch-export">
            <span className="text-xs font-medium">Batch export</span>
            <label className="flex items-center gap-2 text-xs">
              <span className="text-muted-foreground">Platform:</span>
              <select
                data-testid="batch-platform-select"
                className="flex-1 rounded-md border bg-background px-2 py-1"
                value={platformId}
                onChange={(e) => setPlatformId(e.target.value)}
              >
                {PLATFORM_PRESETS.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name} ({p.aspectRatio})
                  </option>
                ))}
              </select>
            </label>
            {batch && (
              <span className="text-xs text-muted-foreground" data-testid="batch-progress">
                {batch.done}/{batch.total} exported
                {batch.failed ? ` · ${batch.failed} failed` : ''}
                {batch.running ? ' …' : ''}
              </span>
            )}
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="secondary"
                data-testid="batch-export-start"
                disabled={approvedClips.length === 0 || !!batch?.running}
                onClick={() => void runBatch()}
              >
                {batch?.running ? 'Exporting…' : `Export all approved (${approvedClips.length})`}
              </Button>
              {batch?.running && (
                <Button
                  size="sm"
                  variant="destructive"
                  data-testid="batch-cancel"
                  onClick={() => batchAbort.current?.abort()}
                >
                  Cancel all
                </Button>
              )}
            </div>
          </div>
        </>
      )}
    </div>
  )
}

export default ExportPanel
