/**
 * ExportPanel — pick a clip, choose an output folder (save dialog), run the
 * export with live progress, then "open folder" (EXPORT spine, plan E.5;
 * PRD §6.9 / §11.2). The pure orchestration (save dialog → export job → reveal)
 * lives in `export-run.ts` (unit-tested against the mock bridge); this is the UI
 * shell. The exported clip set reflects LIVE slice state via
 * `composeProject()` + `buildExportParams()` (integration-gap fix, task 5).
 */

import { useCallback, useMemo, useState } from 'react'
import { useProjectStore } from '@renderer/stores/projectStore'
import { buildExportParams } from '@renderer/stores/projectStore/exportSlice'
import {
  exportToFile,
  openExportFolder,
  defaultClipFileName
} from '@renderer/components/export-run'
import { resolveBounds } from '@shared/clip-bounds'
import { Button } from '@renderer/components/ui/button'
import { Progress } from '@renderer/components/ui/progress'

type Phase = 'idle' | 'exporting' | 'done' | 'error'

export function ExportPanel(): React.JSX.Element {
  const currentProject = useProjectStore((s) => s.currentProject)
  const clips = useProjectStore((s) => s.clips)
  const selectedClipId = useProjectStore((s) => s.selectedClipId)
  const selectClip = useProjectStore((s) => s.selectClip)
  const composeProject = useProjectStore((s) => s.composeProject)
  const addExportRecord = useProjectStore((s) => s.addExportRecord)

  const transcript = useProjectStore((s) => s.transcript)

  const [pct, setPct] = useState(0)
  const [phase, setPhase] = useState<Phase>('idle')
  const [err, setErr] = useState<string | null>(null)
  const [outputPath, setOutputPath] = useState<string | null>(null)
  // Burn word-level karaoke captions into the export (PRD §6.4). On by default
  // when the project has transcript words; the .ass is generated by the runner.
  const [captionsEnabled, setCaptionsEnabled] = useState(true)

  const words = transcript?.words ?? currentProject?.transcript.words ?? []
  const hasWords = words.length > 0

  // The clip to export: the explicitly-selected one, else the first clip.
  const clip = useMemo(
    () => clips.find((c) => c.id === selectedClipId) ?? clips[0] ?? null,
    [clips, selectedClipId]
  )
  const span = clip ? resolveBounds(clip) : null
  const aspectRatio = currentProject?.settings.aspectRatio ?? '9:16'

  const runExport = useCallback(async (): Promise<void> => {
    if (!clip || !currentProject) return
    // Compose from LIVE slices so the exported span/source reflect current edits.
    const project = composeProject()
    if (!project) return

    setPhase('exporting')
    setErr(null)
    setPct(0)
    setOutputPath(null)
    try {
      const outcome = await exportToFile({
        bridge: window.openclip,
        defaultFileName: defaultClipFileName(clip.title),
        buildParams: (chosenPath) =>
          buildExportParams({
            projectId: project.id,
            clip,
            source: project.sourceVideo,
            settings: project.settings,
            outputPath: chosenPath,
            captionsEnabled: captionsEnabled && hasWords,
            words: project.transcript.words
          }),
        onProgress: (p) => setPct(Math.round(p))
      })
      if (outcome.canceled) {
        setPhase('idle')
        return
      }
      setOutputPath(outcome.outputPath)
      addExportRecord({
        id: `exp-${Date.now().toString(36)}`,
        clipId: clip.id,
        outputPath: outcome.outputPath,
        exportedAt: Date.now(),
        width: outcome.result.width,
        height: outcome.result.height,
        format: 'mp4'
      })
      setPhase('done')
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
      setPhase('error')
    }
  }, [clip, currentProject, composeProject, addExportRecord, captionsEnabled, hasWords])

  const reveal = useCallback(async (): Promise<void> => {
    if (outputPath) await openExportFolder(window.openclip, outputPath)
  }, [outputPath])

  return (
    <div data-testid="export-panel" className="flex flex-col gap-3 p-3 text-sm">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Export
      </h2>

      {!clip && (
        <p className="text-muted-foreground" data-testid="export-no-clip">
          No clip selected — generate or pick a clip first.
        </p>
      )}

      {clip && (
        <>
          <div className="flex flex-col gap-1">
            <span className="font-medium" data-testid="export-clip-title">
              {clip.title}
            </span>
            {span && (
              <span className="text-xs text-muted-foreground" data-testid="export-clip-span">
                {span.start.toFixed(2)}s – {span.end.toFixed(2)}s (
                {(span.end - span.start).toFixed(2)}s) · {aspectRatio} · 1080×1920
              </span>
            )}
          </div>

          {/* Word-level karaoke captions toggle (PRD §6.4). */}
          <label className="flex items-center gap-2 text-xs" data-testid="export-captions-toggle">
            <input
              type="checkbox"
              checked={captionsEnabled && hasWords}
              disabled={!hasWords}
              onChange={(e) => setCaptionsEnabled(e.target.checked)}
            />
            <span className={hasWords ? '' : 'text-muted-foreground'}>
              Burn karaoke captions{hasWords ? '' : ' (no transcript)'}
            </span>
          </label>

          {/* Quick clip picker when multiple clips exist. */}
          {clips.length > 1 && (
            <label className="flex items-center gap-2 text-xs">
              <span className="text-muted-foreground">Clip:</span>
              <select
                data-testid="export-clip-select"
                className="flex-1 rounded-md border bg-background px-2 py-1"
                value={clip.id}
                onChange={(e) => selectClip(e.target.value)}
              >
                {clips.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.title}
                  </option>
                ))}
              </select>
            </label>
          )}

          {phase === 'exporting' && (
            <div className="flex flex-col gap-1">
              <Progress value={pct} data-testid="export-progress" />
              <span className="text-xs text-muted-foreground">{pct}%</span>
            </div>
          )}

          {phase === 'done' && (
            <span className="text-xs text-green-600" data-testid="export-done">
              Exported to {outputPath}
            </span>
          )}

          {phase === 'error' && err && (
            <span className="text-xs text-destructive" role="alert" data-testid="export-error">
              {err}
            </span>
          )}

          <div className="flex gap-2">
            <Button
              size="sm"
              data-testid="export-start"
              disabled={phase === 'exporting'}
              onClick={() => void runExport()}
            >
              {phase === 'exporting' ? 'Exporting…' : 'Export clip'}
            </Button>
            {phase === 'done' && outputPath && (
              <Button
                size="sm"
                variant="secondary"
                data-testid="export-open-folder"
                onClick={() => void reveal()}
              >
                Open folder
              </Button>
            )}
          </div>
        </>
      )}
    </div>
  )
}

export default ExportPanel
