/**
 * ExportPanel — pick a clip, choose an output folder (save dialog), run the
 * export with live progress, then "open folder" (EXPORT spine, plan E.5;
 * PRD §6.9 / §11.2). The pure orchestration (save dialog → export job → reveal)
 * lives in `export-run.ts` (unit-tested against the mock bridge); this is the UI
 * shell. The exported clip set reflects LIVE slice state via
 * `composeProject()` + `buildExportParams()` (integration-gap fix, task 5).
 */

import { useCallback, useMemo, useState } from 'react'
import { useProjectStore } from '@renderer/stores/projectStore'
import { buildExportParams } from '@renderer/stores/projectStore/exportSlice'
import {
  exportToFile,
  openExportFolder,
  defaultClipFileName
} from '@renderer/components/export-run'
import { CAPTION_PRESETS, resolveEffectiveCaptionStyle } from '@renderer/components/captionPresets'
import { resolveBounds } from '@shared/clip-bounds'
import { Button } from '@renderer/components/ui/button'
import { Progress } from '@renderer/components/ui/progress'

type Phase = 'idle' | 'exporting' | 'done' | 'error'

/** A selectable caption-template chip (Part K gallery). */
function TemplateChip(props: {
  label: string
  title?: string
  active: boolean
  onClick: () => void
}): React.JSX.Element {
  return (
    <button
      type="button"
      data-testid="caption-template-chip"
      data-active={props.active}
      title={props.title}
      onClick={props.onClick}
      className={`rounded-full border px-2.5 py-1 text-xs transition-colors ${
        props.active
          ? 'border-primary bg-primary text-primary-foreground'
          : 'border-border bg-background hover:bg-accent'
      }`}
    >
      {props.label}
    </button>
  )
}

export function ExportPanel(): React.JSX.Element {
  const currentProject = useProjectStore((s) => s.currentProject)
  const clips = useProjectStore((s) => s.clips)
  const selectedClipId = useProjectStore((s) => s.selectedClipId)
  const selectClip = useProjectStore((s) => s.selectClip)
  const composeProject = useProjectStore((s) => s.composeProject)
  const addExportRecord = useProjectStore((s) => s.addExportRecord)
  const setProjectSettings = useProjectStore((s) => s.setProjectSettings)

  const transcript = useProjectStore((s) => s.transcript)

  const [pct, setPct] = useState(0)
  const [phase, setPhase] = useState<Phase>('idle')
  const [err, setErr] = useState<string | null>(null)
  const [outputPath, setOutputPath] = useState<string | null>(null)
  // Burn word-level karaoke captions into the export (PRD §6.4). On by default
  // when the project has transcript words; the .ass is generated by the runner.
  const [captionsEnabled, setCaptionsEnabled] = useState(true)
  // Remove long silences via jump-cuts (Part I.4, opt-in, default off).
  const [removeSilence, setRemoveSilence] = useState(false)
  // Auto-reframe (Part J, opt-in, default off): follow the speaker / split-screen.
  const [reframe, setReframe] = useState<'off' | 'auto' | 'split'>('off')

  const words = transcript?.words ?? currentProject?.transcript.words ?? []
  const hasWords = words.length > 0

  // The clip to export: the explicitly-selected one, else the first clip.
  const clip = useMemo(
    () => clips.find((c) => c.id === selectedClipId) ?? clips[0] ?? null,
    [clips, selectedClipId]
  )
  const span = clip ? resolveBounds(clip) : null
  const aspectRatio = currentProject?.settings.aspectRatio ?? '9:16'
  // Caption template (Part K) — PERSISTED on the project so the export and the
  // (Step 3) WYSIWYG preview always agree. '' ⇒ the app-default karaoke style.
  const captionTemplateId = currentProject?.settings.captionTemplateId ?? ''

  const runExport = useCallback(async (): Promise<void> => {
    if (!clip || !currentProject) return
    // Compose from LIVE slices so the exported span/source reflect current edits.
    const project = composeProject()
    if (!project) return

    setPhase('exporting')
    setErr(null)
    setPct(0)
    setOutputPath(null)
    try {
      const outcome = await exportToFile({
        bridge: window.openclip,
        defaultFileName: defaultClipFileName(clip.title),
        buildParams: (chosenPath) =>
          buildExportParams({
            projectId: project.id,
            clip,
            source: project.sourceVideo,
            settings: project.settings,
            outputPath: chosenPath,
            captionsEnabled: captionsEnabled && hasWords,
            words: project.transcript.words,
            captionStyle: resolveEffectiveCaptionStyle(captionTemplateId),
            removeSilence,
            reframe
          }),
        onProgress: (p) => setPct(Math.round(p))
      })
      if (outcome.canceled) {
        setPhase('idle')
        return
      }
      setOutputPath(outcome.outputPath)
      addExportRecord({
        id: `exp-${Date.now().toString(36)}`,
        clipId: clip.id,
        outputPath: outcome.outputPath,
        exportedAt: Date.now(),
        width: outcome.result.width,
        height: outcome.result.height,
        format: 'mp4'
      })
      setPhase('done')
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
      setPhase('error')
    }
  }, [
    clip,
    currentProject,
    composeProject,
    addExportRecord,
    captionsEnabled,
    hasWords,
    captionTemplateId,
    removeSilence,
    reframe
  ])

  const reveal = useCallback(async (): Promise<void> => {
    if (outputPath) await openExportFolder(window.openclip, outputPath)
  }, [outputPath])

  return (
    <div data-testid="export-panel" className="flex flex-col gap-3 p-3 text-sm">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
        Export
      </h2>

      {!clip && (
        <p className="text-muted-foreground" data-testid="export-no-clip">
          No clip selected — generate or pick a clip first.
        </p>
      )}

      {clip && (
        <>
          <div className="flex flex-col gap-1">
            <span className="font-medium" data-testid="export-clip-title">
              {clip.title}
            </span>
            {span && (
              <span className="text-xs text-muted-foreground" data-testid="export-clip-span">
                {span.start.toFixed(2)}s – {span.end.toFixed(2)}s (
                {(span.end - span.start).toFixed(2)}s) · {aspectRatio} · 1080×1920
              </span>
            )}
          </div>

          {/* Word-level karaoke captions toggle (PRD §6.4). */}
          <label className="flex items-center gap-2 text-xs" data-testid="export-captions-toggle">
            <input
              type="checkbox"
              checked={captionsEnabled && hasWords}
              disabled={!hasWords}
              onChange={(e) => setCaptionsEnabled(e.target.checked)}
            />
            <span className={hasWords ? '' : 'text-muted-foreground'}>
              Burn karaoke captions{hasWords ? '' : ' (no transcript)'}
            </span>
          </label>

          {/* Caption template gallery (Part K). Persisted on the project so the
              export + the WYSIWYG preview agree. A chip per template. */}
          {captionsEnabled && hasWords && (
            <div className="flex flex-col gap-1.5" data-testid="caption-template-gallery">
              <span className="text-xs text-muted-foreground">Caption template:</span>
              <div className="flex flex-wrap gap-1.5">
                <TemplateChip
                  label="Default"
                  active={captionTemplateId === ''}
                  onClick={() => setProjectSettings({ captionTemplateId: '' })}
                />
                {CAPTION_PRESETS.map((p) => (
                  <TemplateChip
                    key={p.id}
                    label={p.name}
                    title={p.description}
                    active={captionTemplateId === p.id}
                    onClick={() => setProjectSettings({ captionTemplateId: p.id })}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Silence/filler jump-cuts (Part I.4, opt-in). */}
          <label className="flex items-center gap-2 text-xs" data-testid="remove-silence-toggle">
            <input
              type="checkbox"
              checked={removeSilence}
              onChange={(e) => setRemoveSilence(e.target.checked)}
            />
            <span>Remove silences (tighten the clip)</span>
          </label>

          {/* Auto-reframe (Part J, opt-in). Off = static center-crop. */}
          <label className="flex items-center gap-2 text-xs" data-testid="reframe-control">
            <span className="text-muted-foreground">Reframe:</span>
            <select
              data-testid="reframe-select"
              className="flex-1 rounded-md border bg-background px-2 py-1"
              value={reframe}
              onChange={(e) => setReframe(e.target.value as 'off' | 'auto' | 'split')}
            >
              <option value="off">Off (center)</option>
              <option value="auto">Follow speaker</option>
              <option value="split">Split-screen (2 people)</option>
            </select>
          </label>

          {/* Quick clip picker when multiple clips exist. */}
          {clips.length > 1 && (
            <label className="flex items-center gap-2 text-xs">
              <span className="text-muted-foreground">Clip:</span>
              <select
                data-testid="export-clip-select"
                className="flex-1 rounded-md border bg-background px-2 py-1"
                value={clip.id}
                onChange={(e) => selectClip(e.target.value)}
              >
                {clips.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.title}
                  </option>
                ))}
              </select>
            </label>
          )}

          {phase === 'exporting' && (
            <div className="flex flex-col gap-1">
              <Progress value={pct} data-testid="export-progress" />
              <span className="text-xs text-muted-foreground">{pct}%</span>
            </div>
          )}

          {phase === 'done' && (
            <span className="text-xs text-green-600" data-testid="export-done">
              Exported to {outputPath}
            </span>
          )}

          {phase === 'error' && err && (
            <span className="text-xs text-destructive" role="alert" data-testid="export-error">
              {err}
            </span>
          )}

          <div className="flex gap-2">
            <Button
              size="sm"
              data-testid="export-start"
              disabled={phase === 'exporting'}
              onClick={() => void runExport()}
            >
              {phase === 'exporting' ? 'Exporting…' : 'Export clip'}
            </Button>
            {phase === 'done' && outputPath && (
              <Button
                size="sm"
                variant="secondary"
                data-testid="export-open-folder"
                onClick={() => void reveal()}
              >
                Open folder
              </Button>
            )}
          </div>
        </>
      )}
    </div>
  )
}

export default ExportPanel
